"""empty message

Revision ID: f51bff4bbd24
Revises: c2836e4374a1
Create Date: 2023-09-20 10:17:18.051888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f51bff4bbd24'
down_revision = 'c2836e4374a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(), nullable=False))
        batch_op.drop_column('url')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('quantity',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('quantity',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('product_images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('image')

    # ### end Alembic commands ###